services:
  postgres:
    container_name: db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/val/lib/postgresql/data

  minio:
    container_name: minio
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/val/lib/minio/data

  mailHog:
    container_name: mailHog
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
      - "1025:1025"


volumes:
  pgdata:
  minio_data: