services:
  postgres:
    container_name: db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgres/data

  minio:
    container_name: minio
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/val/lib/minio/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/val/lib/redis/data
    command: redis-server --appendonly yes

  mailHog:
    container_name: mailHog
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
      - "1025:1025"


volumes:
  postgres_data:
  minio_data:
  redis_data: